set_location_assignment PIN_H8  -to gpio_d[0]
set_location_assignment PIN_K10 -to gpio_d[1]
set_location_assignment PIN_H5  -to gpio_d[2]
set_location_assignment PIN_H4  -to gpio_d[3]
set_location_assignment PIN_J1  -to gpio_d[4]
set_location_assignment PIN_J2  -to gpio_d[5]
set_location_assignment PIN_L12 -to gpio_d[6]
set_location_assignment PIN_J12 -to gpio_d[7]
set_location_assignment PIN_J13 -to gpio_d[8]
set_location_assignment PIN_K11 -to gpio_d[9]
set_location_assignment PIN_K12 -to gpio_d[10]
set_location_assignment PIN_J10 -to gpio_d[11]
set_location_assignment PIN_H10 -to gpio_d[12]
set_location_assignment PIN_H13 -to gpio_d[13]
set_location_assignment PIN_G12 -to gpio_d[14]

set_location_assignment PIN_E1 -to gpio_a[0]
set_location_assignment PIN_C2 -to gpio_a[1]
set_location_assignment PIN_C1 -to gpio_a[2]
set_location_assignment PIN_D1 -to gpio_a[3]
set_location_assignment PIN_E3 -to gpio_a[4]
set_location_assignment PIN_F1 -to gpio_a[5]
set_location_assignment PIN_E4 -to gpio_a[6]
set_location_assignment PIN_B1 -to gpio_a[7]

set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to gpio_*
